# This profile contains cross-platform profile stuffs. Anything that is
#   machine specific goes in ~/.local_profile

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

source ~/.env
source ~/.prompt
source ~/.alias

# Add home directory bin to path
export PATH=$PATH:$HOME/bin

# If I want some default python code to run when I start the interpreter
#export PYTHONSTARTUP="$HOME/.python_startup.py"

if [[ -a ~/.local_profile ]]
then
  source ~/.local_profile
fi