# This profile contains cross-platform profile stuffs. Anything that is
#   machine specific goes in ~/.local_profile

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

source ~/.env
source ~/.prompt
source ~/.alias

# Add home directory bin to path
export PATH=$PATH:$HOME/bin

# Ruby/JEkyll
export PATH=$PATH:/Users/apricewhelan/.gem/ruby/2.6.0/bin

# If I want some default python code to run when I start the interpreter
# export PYTHONSTARTUP="$HOME/.python_startup.py"

export PATH=/usr/local/bin:$PATH:/opt/local/bin

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/apricewhelan/anaconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/apricewhelan/anaconda/etc/profile.d/conda.sh" ]; then
        . "/Users/apricewhelan/anaconda/etc/profile.d/conda.sh"
    else
        export PATH="/Users/apricewhelan/anaconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export MACOSX_DEPLOYMENT_TARGET="10.9"

# For installing EXP
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/local/share/pkgconfig:/opt/local/lib/pkgconfig/
export C_INCLUDE_PATH=$C_INCLUDE_PATH:/opt/local/include/
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/opt/local/include/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/local/lib/
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
